name: Sanity

on:
  push:
    branches-ignore:
      - main

jobs:
  sanity:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
